// <auto-generated />
using System;
using RelationsPlatform.Persistence.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RelationsPlatform.Persistence.Infrastructure.Migrations
{
    [DbContext(typeof(RelationsPlatformDataBaseContext))]
    partial class DisciplinePickerDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        }

        //        protected override void BuildModel(ModelBuilder modelBuilder)
        //        {
        //#pragma warning disable 612, 618
        //            modelBuilder
        //                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
        //                .HasAnnotation("Relational:MaxIdentifierLength", 128)
        //                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.Discipline", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<string>("Department");

        //                    b.Property<string>("Description");

        //                    b.Property<string>("Faculty");

        //                    b.Property<string>("Name");

        //                    b.HasKey("Id");

        //                    b.ToTable("Disciplines");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("0874505b-c85f-4df0-aa4f-68069ef1e656"),
        //                            Department = "Department1",
        //                            Description = "Description1",
        //                            Faculty = "Faculty1",
        //                            Name = "Discipline1"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("13ff5772-8d9b-465f-9b23-654143740a09"),
        //                            Department = "Department2",
        //                            Description = "Description2",
        //                            Faculty = "Faculty2",
        //                            Name = "Discipline2"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("ec5554e8-b31b-40ca-ab2f-fe4cdd6a6dab"),
        //                            Department = "Department3",
        //                            Description = "Description3",
        //                            Faculty = "Faculty3",
        //                            Name = "Discipline3"
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.DisciplineAvailability", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<Guid>("DisciplineId");

        //                    b.Property<int>("Hours");

        //                    b.Property<Guid>("LecturerId");

        //                    b.Property<int>("MaxAllovedStudents");

        //                    b.Property<int>("MinAllovedStudents");

        //                    b.Property<int>("Semester");

        //                    b.Property<int>("Year");

        //                    b.HasKey("Id");

        //                    b.HasIndex("DisciplineId");

        //                    b.HasIndex("LecturerId");

        //                    b.ToTable("DisciplineAvailabilities");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("08124a13-c3db-4dfe-8760-b084d3b2ed49"),
        //                            DisciplineId = new Guid("0874505b-c85f-4df0-aa4f-68069ef1e656"),
        //                            Hours = 90,
        //                            LecturerId = new Guid("25541f87-9939-43b2-b190-7440b2ab5571"),
        //                            MaxAllovedStudents = 200,
        //                            MinAllovedStudents = 25,
        //                            Semester = 6,
        //                            Year = 2020
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("58e61323-d9ba-4190-a5aa-82ef2b57f25b"),
        //                            DisciplineId = new Guid("0874505b-c85f-4df0-aa4f-68069ef1e656"),
        //                            Hours = 90,
        //                            LecturerId = new Guid("9d2edad8-b371-4995-a5af-81b97ba5080b"),
        //                            MaxAllovedStudents = 200,
        //                            MinAllovedStudents = 25,
        //                            Semester = 7,
        //                            Year = 2020
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("9814c8b5-935a-4e8b-9b2e-8d5341f94a4d"),
        //                            DisciplineId = new Guid("13ff5772-8d9b-465f-9b23-654143740a09"),
        //                            Hours = 90,
        //                            LecturerId = new Guid("4f38f789-cae6-45a8-9806-dff3380ccd12"),
        //                            MaxAllovedStudents = 200,
        //                            MinAllovedStudents = 25,
        //                            Semester = 5,
        //                            Year = 2020
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.DisciplineChoise", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<Guid>("DisciplineAvailabilityId");

        //                    b.Property<Guid>("StudentId");

        //                    b.HasKey("Id");

        //                    b.HasIndex("DisciplineAvailabilityId");

        //                    b.HasIndex("StudentId");

        //                    b.ToTable("DisciplineChoises");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("ed10cc99-2f36-47b1-a4f2-4b48860011e4"),
        //                            DisciplineAvailabilityId = new Guid("08124a13-c3db-4dfe-8760-b084d3b2ed49"),
        //                            StudentId = new Guid("3b4e5908-7842-4523-9ea6-bb14befb3d0e")
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("10b8730d-5d7e-4b35-9c92-2c08cc98d0af"),
        //                            DisciplineAvailabilityId = new Guid("58e61323-d9ba-4190-a5aa-82ef2b57f25b"),
        //                            StudentId = new Guid("3b4e5908-7842-4523-9ea6-bb14befb3d0e")
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("c968e07a-d89a-426b-afa6-cb6e761bdfd6"),
        //                            DisciplineAvailabilityId = new Guid("08124a13-c3db-4dfe-8760-b084d3b2ed49"),
        //                            StudentId = new Guid("8b827de2-61a0-42ed-81b5-7360aad5664f")
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.Lecturer", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<string>("Department");

        //                    b.Property<string>("Faculty");

        //                    b.Property<string>("Name");

        //                    b.HasKey("Id");

        //                    b.ToTable("Lecturers");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("4f38f789-cae6-45a8-9806-dff3380ccd12"),
        //                            Department = "Інформаційних систем",
        //                            Faculty = "Прикладна математика",
        //                            Name = "Тарасюк Іван"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("9d2edad8-b371-4995-a5af-81b97ba5080b"),
        //                            Department = "Інформаційних систем",
        //                            Faculty = "Прикладна математика",
        //                            Name = "Ім'я Прізвище"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("25541f87-9939-43b2-b190-7440b2ab5571"),
        //                            Department = "Інформаційних систем",
        //                            Faculty = "Прикладна математика",
        //                            Name = "Ім'я Прізвище2"
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.Role", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<string>("Name");

        //                    b.HasKey("Id");

        //                    b.ToTable("Roles");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("2432fe24-3a95-4bfe-85bd-4191cd41b230"),
        //                            Name = "admin"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Name = "student"
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.Student", b =>
        //                {
        //                    b.Property<Guid>("Id")
        //                        .ValueGeneratedOnAdd();

        //                    b.Property<int>("Course");

        //                    b.Property<string>("Department");

        //                    b.Property<string>("Group");

        //                    b.Property<string>("Login");

        //                    b.Property<string>("Name");

        //                    b.Property<string>("Password");

        //                    b.Property<byte[]>("Photo");

        //                    b.Property<Guid>("RoleId");

        //                    b.Property<string>("Speciality");

        //                    b.HasKey("Id");

        //                    b.HasIndex("RoleId");

        //                    b.ToTable("Students");

        //                    b.HasData(
        //                        new
        //                        {
        //                            Id = new Guid("1f444245-51e5-452a-bdab-6010e82b8937"),
        //                            Course = 0,
        //                            Login = "admin.com",
        //                            Password = "123",
        //                            RoleId = new Guid("2432fe24-3a95-4bfe-85bd-4191cd41b230")
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("3b4e5908-7842-4523-9ea6-bb14befb3d0e"),
        //                            Course = 3,
        //                            Department = "Інформаційних систем",
        //                            Group = "Gp37",
        //                            Login = "bozhook@gmail.com",
        //                            Name = "Віктор Божук",
        //                            Password = "123456aA_",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Комп'ютерні науки"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("8b827de2-61a0-42ed-81b5-7360aad5664f"),
        //                            Course = 3,
        //                            Department = "Інформаційних систем",
        //                            Group = "Gp38",
        //                            Login = "B@gmail.com",
        //                            Name = "Власюк Василь",
        //                            Password = "123456aA_",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Комп'ютерні науки"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("2a2b6f7b-7084-4241-86da-fe19cbb39d4c"),
        //                            Course = 3,
        //                            Department = "Інформаційних систем",
        //                            Group = "Gp39",
        //                            Login = "M@gmail.com",
        //                            Name = "Щерба Максим",
        //                            Password = "123456aA_",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Комп'ютерні науки"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("d8ed0233-40a4-44a1-85a6-8191c4a99683"),
        //                            Course = 2,
        //                            Department = "Інформаційних систем нейронних",
        //                            Group = "Gp40",
        //                            Login = "А@gmail.com",
        //                            Name = "Альфа Дельта",
        //                            Password = "1234",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Комп'ютерні науки богарта"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("3392ed82-0a7a-42db-b50d-61e1b0b1380d"),
        //                            Course = 1,
        //                            Department = "Риторичних систем нейронних",
        //                            Group = "Gp42",
        //                            Login = "В@gmail.com",
        //                            Name = "Браво Фокстрот",
        //                            Password = "1234",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Міщанські науки"
        //                        },
        //                        new
        //                        {
        //                            Id = new Guid("0a6808c6-f0b5-4a27-95d3-8f1c00f76c99"),
        //                            Course = 3,
        //                            Department = "Інформаційних підсистем",
        //                            Group = "Gp50",
        //                            Login = "А@gmail.com",
        //                            Name = "Лютер Кінг",
        //                            Password = "1234",
        //                            RoleId = new Guid("442d3c5c-8737-4934-bac9-f20f35e99a88"),
        //                            Speciality = "Комп'ютерні монітори"
        //                        });
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.DisciplineAvailability", b =>
        //                {
        //                    b.HasOne("DisciplinePicker.Persistence.Model.Discipline", "Discipline")
        //                        .WithMany("DisciplineAvailabilities")
        //                        .HasForeignKey("DisciplineId")
        //                        .HasConstraintName("FK_Discipline_DisciplineAvailabilities");

        //                    b.HasOne("DisciplinePicker.Persistence.Model.Lecturer", "Lecturer")
        //                        .WithMany("DisciplineAvailabilities")
        //                        .HasForeignKey("LecturerId")
        //                        .HasConstraintName("FK_Lecturer_DisciplineAvailabilities");
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.DisciplineChoise", b =>
        //                {
        //                    b.HasOne("DisciplinePicker.Persistence.Model.DisciplineAvailability", "DisciplineAvailability")
        //                        .WithMany("DisciplineChoises")
        //                        .HasForeignKey("DisciplineAvailabilityId")
        //                        .HasConstraintName("FK_DisciplineChoise_DisciplineAvailability");

        //                    b.HasOne("DisciplinePicker.Persistence.Model.Student", "Student")
        //                        .WithMany("DisciplineChoises")
        //                        .HasForeignKey("StudentId")
        //                        .HasConstraintName("FK_DisciplineChoise_Student");
        //                });

        //            modelBuilder.Entity("DisciplinePicker.Persistence.Model.Student", b =>
        //                {
        //                    b.HasOne("DisciplinePicker.Persistence.Model.Role", "Role")
        //                        .WithMany("Students")
        //                        .HasForeignKey("RoleId")
        //                        .OnDelete(DeleteBehavior.Cascade);
        //                });
        //#pragma warning restore 612, 618
        //        }
    }
}
